#define _boolean 1
#define _break 2
#define _class 3
#define _double 4
#define _else 5
#define _extends 6
#define _false 7
#define _for 8
#define _if 9
#define _implements 10
#define _int 11
#define _interface 12
#define _newarray 13
#define _println 14
#define _readln 15
#define _return 16
#define _string 17
#define _void 18
#define _while 19
#define _plus 20
#define _minus 21
#define _multiplication 22
#define _division 23
#define _mod 24
#define _less 25
#define _lessequal 26
#define _greater 27
#define _greaterequal 28
#define _equal 29
#define _notequal 30
#define _and 31
#define _or 32
#define _not 33 
#define _assignop 34
#define _semicolon 35
#define _comma 36
#define _period 37
#define _leftparen 38
#define _rightparen 39
#define _leftbracket 40
#define _rightbracket 41
#define _leftbrace 42
#define _rightbrace 43
#define _intconstant 44
#define _doubleconstant 45
#define _stringconstant 46
#define _booleanconstant 47
#define _id 48